import { jsPDF } from 'jspdf'
import type { OrderDetails } from '@/lib/services/order.service'
import type { LicenseKey } from '@/lib/services/keys.service'
import { formatOrderDate } from './order-formatters'

const BRAND_BLUE = [59, 130, 246] as const
const DARK_BG = [17, 24, 39] as const
const TEXT_WHITE = [255, 255, 255] as const
const TEXT_MUTED = [156, 163, 175] as const
const BORDER_COLOR = [55, 65, 81] as const
const KEY_BG = [31, 41, 55] as const
const WARNING_AMBER = [245, 158, 11] as const

function drawLine(doc: jsPDF, y: number, width: number) {
  doc.setDrawColor(...BORDER_COLOR)
  doc.setLineWidth(0.3)
  doc.line(20, y, width - 20, y)
}

function ensurePage(doc: jsPDF, y: number, needed: number): number {
  const pageHeight = doc.internal.pageSize.getHeight()
  const pageWidth = doc.internal.pageSize.getWidth()
  if (y + needed > pageHeight - 20) {
    doc.addPage()
    doc.setFillColor(...DARK_BG)
    doc.rect(0, 0, pageWidth, pageHeight, 'F')
    return 20
  }
  return y
}

export function generateKeysPdf(
  order: OrderDetails,
  keysData: LicenseKey[] = [],
): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()

  // — Dark background
  doc.setFillColor(...DARK_BG)
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F')

  let y = 20

  // — Header
  doc.setFontSize(22)
  doc.setTextColor(...TEXT_WHITE)
  doc.setFont('helvetica', 'bold')
  doc.text('Increddy', 20, y)

  doc.setFontSize(12)
  doc.setTextColor(...BRAND_BLUE)
  doc.setFont('helvetica', 'bold')
  doc.text('PRODUCT KEYS', pageWidth - 20, y, { align: 'right' })

  y += 10

  // — Order info line
  doc.setFontSize(9)
  doc.setTextColor(...TEXT_MUTED)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `Order #${order.orderNumber}  |  ${order.processedAt ? formatOrderDate(order.processedAt) : '-'}`,
    20,
    y,
  )

  y += 6
  drawLine(doc, y, pageWidth)
  y += 10

  // — Warning banner
  doc.setFillColor(...KEY_BG)
  doc.roundedRect(20, y, pageWidth - 40, 12, 2, 2, 'F')
  doc.setFontSize(9)
  doc.setTextColor(...WARNING_AMBER)
  doc.setFont('helvetica', 'bold')
  doc.text(
    'Keep your keys confidential. Do not share this document.',
    pageWidth / 2,
    y + 7.5,
    { align: 'center' },
  )
  y += 20

  // — Line items with keys
  const lineItems = order.lineItems?.edges ?? []

  for (const item of lineItems) {
    const node = item.node
    const productTitle = node?.title || 'Untitled Product'
    const variant = node?.variant
    const variantName =
      variant?.title && variant.title !== 'Default Title'
        ? ` — ${variant.title}`
        : ''

    // Match real keys by variant_id
    const variantGid = variant?.id ?? ''
    const keys = keysData
      .filter((k) => k.variant_id === variantGid)
      .map((k) => k.license_key)

    if (keys.length === 0) {
      keys.push('No keys available')
    }

    // Product title
    y = ensurePage(doc, y, 20 + keys.length * 12)

    doc.setFontSize(12)
    doc.setTextColor(...TEXT_WHITE)
    doc.setFont('helvetica', 'bold')
    const titleLines = doc.splitTextToSize(
      `${productTitle}${variantName}`,
      pageWidth - 40,
    )
    doc.text(titleLines, 20, y)
    y += titleLines.length * 6

    doc.setFontSize(9)
    doc.setTextColor(...TEXT_MUTED)
    doc.setFont('helvetica', 'normal')
    doc.text(`Quantity: ${node?.quantity ?? 1}`, 20, y)
    y += 8

    // Keys
    for (const key of keys) {
      y = ensurePage(doc, y, 14)

      // Key background pill
      const pillHeight = 10
      doc.setFillColor(...KEY_BG)
      doc.roundedRect(20, y, pageWidth - 40, pillHeight, 2, 2, 'F')

      doc.setFontSize(11)
      doc.setTextColor(...TEXT_WHITE)
      doc.setFont('courier', 'bold')
      doc.text(key, 26, y + pillHeight / 2 + 1.5)
      y += pillHeight + 4
    }

    y += 4
    drawLine(doc, y, pageWidth)
    y += 10
  }

  // — Footer
  y = ensurePage(doc, y, 15)
  doc.setFontSize(8)
  doc.setTextColor(...TEXT_MUTED)
  doc.setFont('helvetica', 'normal')
  doc.text(
    'Generated by Increddy. These keys are for your personal use only.',
    pageWidth / 2,
    y,
    { align: 'center' },
  )

  doc.save(`Increddy-Keys-${order.orderNumber}.pdf`)
}
