// Automatically generated from Driffle's exact supported locales
export const countries = [
  { value: 'US', label: 'United States', flag: '🇺🇸' },
  { value: 'GB', label: 'United Kingdom', flag: '🇬🇧' },
  { value: 'AT', label: 'Austria', flag: '🇦🇹' },
  { value: 'IN', label: 'India', flag: '🇮🇳' },
  { value: 'RO', label: 'Romania', flag: '🇷🇴' },
]

export const currencies = [
  { value: 'ALL', label: 'Albanian Lek (ALL)' },
  { value: 'DZD', label: 'Algerian Dinar (DZD)' },
  { value: 'ARS', label: 'Argentine Peso (ARS)' },
  { value: 'AMD', label: 'Armeniam Dram (AMD)' },
  { value: 'AWG', label: 'Aruban Florin (AWG)' },
  { value: 'AUD', label: 'Australian Dollar (A$)' },
  { value: 'AZN', label: 'Azerbaijani Manat (AZN)' },
  { value: 'BSD', label: 'Bahamian Dollar (BSD)' },
  { value: 'BHD', label: 'Bahraini Dinar (BHD)' },
  { value: 'BBD', label: 'Bajan Dollar (BBD)' },
  { value: 'BDT', label: 'Bangladeshi Taka (৳)' },
  { value: 'BYN', label: 'Belarusian Ruble (BYN)' },
  { value: 'BZD', label: 'Belize Dollar (BZD)' },
  { value: 'BMD', label: 'Bermudan Dollar (BMD)' },
  { value: 'BTN', label: 'Bhutan Ngultrum (Nu.)' },
  { value: 'BOB', label: 'Bolivian Boliviano (Bs)' },
  { value: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark (KM)' },
  { value: 'BWP', label: 'Botswanan Pula (BWP)' },
  { value: 'BRL', label: 'Brazilian Real (R$)' },
  { value: 'GBP', label: 'British Pound (£)' },
  { value: 'BND', label: 'Brunei Dollar (BND)' },
  { value: 'BGN', label: 'Bulgarian Lev (BGN)' },
  { value: 'BIF', label: 'Burundian Franc (BIF)' },
  { value: 'XPF', label: 'CFP Franc (XPF)' },
  { value: 'KHR', label: 'Cambodian Riel (KHR)' },
  { value: 'CAD', label: 'Canadian Dollar (CAD)' },
  { value: 'CVE', label: 'Cape Verdean Escudo (CVE)' },
  { value: 'KYD', label: 'Cayman Islands Dollar (KYD)' },
  { value: 'XAF', label: 'Central African CFA Franc (XAF)' },
  { value: 'CLP', label: 'Chilean Peso (CLP)' },
  { value: 'CNY', label: 'Chinese Yuan (CNY)' },
  { value: 'COP', label: 'Colombian Peso (COP)' },
  { value: 'KMF', label: 'Comorian Franc (KMF)' },
  { value: 'CDF', label: 'Congolese Franc (CDF)' },
  { value: 'CRC', label: 'Costa Rican Colon (CRC)' },
  { value: 'CZK', label: 'Czech Koruna (CZK)' },
  { value: 'DKK', label: 'Danish Krone (DKK)' },
  { value: 'DJF', label: 'Djiboutian Franc (DJF)' },
  { value: 'DOP', label: 'Dominican Peso (DOP)' },
  { value: 'XCD', label: 'East Caribbean Dollar (XCD)' },
  { value: 'EGP', label: 'Egyptian Pound (EGP)' },
  { value: 'ERN', label: 'Eritrean Nakfa (ERN)' },
  { value: 'ETB', label: 'Ethiopian Birr (ETB)' },
  { value: 'EUR', label: 'Euro (€)' },
  { value: 'FKP', label: 'Falkland Island Pound (FKP)' },
  { value: 'FJD', label: 'Fijian Dollar (FJD)' },
  { value: 'GMD', label: 'Gambian Dalasi (GMD)' },
  { value: 'GEL', label: 'Georgian Lari (GEL)' },
  { value: 'GHS', label: 'Ghanaian Cedi (GHS)' },
  { value: 'GIP', label: 'Gibraltar Pound (GIP)' },
  { value: 'GTQ', label: 'Guatemalan Quetzal (GTQ)' },
  { value: 'GNF', label: 'Guinean Franc (GNF)' },
  { value: 'GYD', label: 'Guyanaese Dollar (GYD)' },
  { value: 'HTG', label: 'Haitian Gourde (HTG)' },
  { value: 'HNL', label: 'Honduran Lempira (HNL)' },
  { value: 'HKD', label: 'Hong Kong Dollar (HK$)' },
  { value: 'HUF', label: 'Hungarian Forint (HUF)' },
  { value: 'ISK', label: 'Icelandic Krona (ISK)' },
  { value: 'INR', label: 'Indian Rupee (₹)' },
  { value: 'IDR', label: 'Indonesian Rupiah (IDR)' },
  { value: 'ILS', label: 'Israeli New Shekel (ILS)' },
  { value: 'JMD', label: 'Jamaican Dollar (JMD)' },
  { value: 'JPY', label: 'Japanese Yen (JPY)' },
  { value: 'JOD', label: 'Jordanian Dinar (JOD)' },
  { value: 'KZT', label: 'Kazakhstani Tenge (KZT)' },
  { value: 'KES', label: 'Kenyan Shilling (KES)' },
  { value: 'KWD', label: 'Kuwaiti Dinar (KWD)' },
  { value: 'KGS', label: 'Kyrgystani Som (KGS)' },
  { value: 'LAK', label: 'Laotian Kip (LAK)' },
  { value: 'LBP', label: 'Lebanese Pound (LBP)' },
  { value: 'LSL', label: 'Lesotho Loti (LSL)' },
  { value: 'LRD', label: 'Liberian Dollar (LRD)' },
  { value: 'LYD', label: 'Libyan Dinar (LYD)' },
  { value: 'MOP', label: 'Macanese Pataca (MOP)' },
  { value: 'MKD', label: 'Macedonian Denar (MKD)' },
  { value: 'MGA', label: 'Malagasy Ariary (MGA)' },
  { value: 'MWK', label: 'Malawian Kwacha (MWK)' },
  { value: 'MYR', label: 'Malaysian Ringgit (MYR)' },
  { value: 'MVR', label: 'Maldivian Rufiyaa (MVR)' },
  { value: 'MRO', label: 'Mauritanian Ouguiya (MRO)' },
  { value: 'MUR', label: 'Mauritian Rupee (MUR)' },
  { value: 'MXN', label: 'Mexican Peso (MXN)' },
  { value: 'MDL', label: 'Moldovan Leu (MDL)' },
  { value: 'MNT', label: 'Mongolian Tugrik (MNT)' },
  { value: 'MAD', label: 'Moroccan Dirham (MAD)' },
  { value: 'MZN', label: 'Mozambican Metical (MZN)' },
  { value: 'NAD', label: 'Namibian Dollar (NAD)' },
  { value: 'NPR', label: 'Nepalese Rupee (NPR)' },
  { value: 'NZD', label: 'New Zealand Dollar (NZ$)' },
  { value: 'NIO', label: 'Nicaraguan Cordoba (NIO)' },
  { value: 'NGN', label: 'Nigerian Naira (NGN)' },
  { value: 'NOK', label: 'Norwegian Krone (NOK)' },
  { value: 'OMR', label: 'Omani Rial (OMR)' },
  { value: 'PKR', label: 'Pakistani Rupee (PKR)' },
  { value: 'PAB', label: 'Panamanian Balboa (PAB)' },
  { value: 'PGK', label: 'Papua New Guinean Kina (PGK)' },
  { value: 'PYG', label: 'Paraguayan Guarani (PYG)' },
  { value: 'PEN', label: 'Peruvian Sol (PEN)' },
  { value: 'PHP', label: 'Philippine Peso (₱)' },
  { value: 'PLN', label: 'Polish Zloty (PLN)' },
  { value: 'QAR', label: 'Qatari Rial (QAR)' },
  { value: 'RON', label: 'Romanian Leu (RON)' },
  { value: 'RWF', label: 'Rwandan Franc (RWF)' },
  { value: 'SHP', label: 'Saint Helenian Pound (SHP)' },
  { value: 'WST', label: 'Samoan Tala (WST)' },
  { value: 'STN', label: 'Sao Tomean Dobra (STN)' },
  { value: 'SAR', label: 'Saudi Riyal (SAR)' },
  { value: 'RSD', label: 'Serbian Dinar (RSD)' },
  { value: 'SCR', label: 'Seychellois Rupee (SCR)' },
  { value: 'SLL', label: 'Sierra Leonean Leone (SLL)' },
  { value: 'SGD', label: 'Singapore Dollar (S$)' },
  { value: 'SBD', label: 'Solomon Islands Dollar (SBD)' },
  { value: 'SOS', label: 'Somali Shilling (SOS)' },
  { value: 'ZAR', label: 'South African Rand (ZAR)' },
  { value: 'KRW', label: 'South Korean Won (KRW)' },
  { value: 'LKR', label: 'Sri Lankan Rupee (LKR)' },
  { value: 'SRD', label: 'Surinamese Dollar (SRD)' },
  { value: 'SZL', label: 'Swazi Lilangeni (SZL)' },
  { value: 'SEK', label: 'Swedish Krona (SEK)' },
  { value: 'CHF', label: 'Swiss Franc (CHF)' },
  { value: 'TJS', label: 'Tajikistani Somoni (TJS)' },
  { value: 'TZS', label: 'Tanzanian Shilling (TZS)' },
  { value: 'THB', label: 'Thai Baht (฿)' },
  { value: 'TTD', label: 'Trinidad & Tobago Dollar (TTD)' },
  { value: 'TND', label: 'Tunisian Dinar (TND)' },
  { value: 'TRY', label: 'Turkish Lira (₺)' },
  { value: 'TMT', label: 'Turkmenistani Manat (TMT)' },
  { value: 'UGX', label: 'Ugandan Shilling (UGX)' },
  { value: 'UAH', label: 'Ukrainian Hryvni (UAH)' },
  { value: 'AED', label: 'United Arab Emirates Dirham (AED)' },
  { value: 'USD', label: 'United States Dollar (US$)' },
  { value: 'UYU', label: 'Uruguayan Peso (UYU)' },
  { value: 'UZS', label: 'Uzbekistani Som (UZS)' },
  { value: 'VUV', label: 'Vanuatu Vatu (VUV)' },
  { value: 'VND', label: 'Vietnamese Dong (VND)' },
  { value: 'XOF', label: 'West African CFA Franc (XOF)' },
  { value: 'ZMW', label: 'Zambian Kwacha (ZMW)' },
  { value: 'ZWL', label: 'Zimbabwean Dollar (ZWL)' },
  { value: 'AOA', label: 'Angolan Kwanza (AOA)' },
  { value: 'TWD', label: 'New Taiwan Dollar (NT$)' },
]

export const languages = [
  { value: 'ID', label: 'bahasa Indonesia' },
  { value: 'PT', label: 'Brasileiro' },
  { value: 'DA', label: 'Dansk' },
  { value: 'DE', label: 'Deutsch' },
  { value: 'EN', label: 'English' },
  { value: 'ES', label: 'Español' },
  { value: 'TL', label: 'Filipino' },
  { value: 'FR', label: 'Français' },
  { value: 'IT', label: 'Italiano' },
  { value: 'LT', label: 'Lietuvių' },
  { value: 'HU', label: 'Magyar' },
  { value: 'NL', label: 'Nederlands' },
  { value: 'PL', label: 'Polski' },
  { value: 'PT', label: 'Português' },
  { value: 'RO', label: 'Română' },
  { value: 'FI', label: 'Suomalainen' },
  { value: 'SV', label: 'Svenska' },
  { value: 'VI', label: 'Tiếng Việt' },
  { value: 'CS', label: 'čeština' },
  { value: 'TR', label: 'турецкий' },
  { value: 'EL', label: 'Ελληνικά' },
  { value: 'RU', label: 'Русский' },
  { value: 'TH', label: 'แบบไทย' },
  { value: 'JA', label: '日本語' },
  { value: 'ZH', label: '简体中文' },
]

export const defaultRegionSettings: Record<
  string,
  { currency: string; language: string }
> = {
  US: { currency: 'USD', language: 'EN' },
  GB: { currency: 'GBP', language: 'EN' },
  IN: { currency: 'INR', language: 'EN' },
  RO: { currency: 'RON', language: 'RO' },
  JP: { currency: 'JPY', language: 'JA' },
  FR: { currency: 'EUR', language: 'FR' },
  DE: { currency: 'EUR', language: 'DE' },
  IT: { currency: 'EUR', language: 'IT' },
  ES: { currency: 'EUR', language: 'ES' },
  AU: { currency: 'AUD', language: 'EN' },
  CA: { currency: 'CAD', language: 'EN' },
  CN: { currency: 'CNY', language: 'ZH' },
  BR: { currency: 'BRL', language: 'PT' },
  RU: { currency: 'RUB', language: 'RU' },
  KR: { currency: 'KRW', language: 'KO' },
  MX: { currency: 'MXN', language: 'ES' },
  TH: { currency: 'THB', language: 'TH' },
  ID: { currency: 'IDR', language: 'ID' },
  TR: { currency: 'TRY', language: 'TR' },
  NL: { currency: 'EUR', language: 'NL' },
  PL: { currency: 'PLN', language: 'PL' },
  SE: { currency: 'SEK', language: 'SV' },
  CH: { currency: 'CHF', language: 'DE' },
  SG: { currency: 'SGD', language: 'EN' },
  NZ: { currency: 'NZD', language: 'EN' },
  SA: { currency: 'SAR', language: 'AR' },
  AE: { currency: 'AED', language: 'AR' },
  ZA: { currency: 'ZAR', language: 'EN' },
  AR: { currency: 'ARS', language: 'ES' },
  CO: { currency: 'COP', language: 'ES' },
  PH: { currency: 'PHP', language: 'TL' },
  VN: { currency: 'VND', language: 'VI' },
  EG: { currency: 'EGP', language: 'AR' },
  NG: { currency: 'NGN', language: 'EN' },
  MY: { currency: 'MYR', language: 'EN' },
  CZ: { currency: 'CZK', language: 'CS' },
  HU: { currency: 'HUF', language: 'HU' },
  IL: { currency: 'ILS', language: 'HE' },
  PT: { currency: 'EUR', language: 'PT' },
  GR: { currency: 'EUR', language: 'EL' },
  DK: { currency: 'DKK', language: 'DA' },
  FI: { currency: 'EUR', language: 'FI' },
  NO: { currency: 'NOK', language: 'NO' },
  IE: { currency: 'EUR', language: 'EN' },
  AT: { currency: 'EUR', language: 'DE' },
  BE: { currency: 'EUR', language: 'NL' },
  BD: { currency: 'BDT', language: 'BN' },
}

export function getCountryForCurrency(currency: string): string {
  const customMap: Record<string, string> = {
    ALL: 'AL', DZD: 'DZ', ARS: 'AR', AMD: 'AM', AWG: 'AW', AUD: 'AU', AZN: 'AZ', BSD: 'BS',
    BHD: 'BH', BBD: 'BB', BDT: 'BD', BYN: 'BY', BZD: 'BZ', BMD: 'BM', BTN: 'BT', BOB: 'BO',
    BAM: 'BA', BWP: 'BW', BRL: 'BR', GBP: 'GB', BND: 'BN', BGN: 'BG', BIF: 'BI', XPF: 'PF',
    KHR: 'KH', CAD: 'CA', CVE: 'CV', KYD: 'KY', XAF: 'CM', CLP: 'CL', CNY: 'CN', COP: 'CO',
    KMF: 'KM', CDF: 'CD', CRC: 'CR', CZK: 'CZ', DKK: 'DK', DJF: 'DJ', DOP: 'DO', XCD: 'AG',
    EGP: 'EG', ERN: 'ER', ETB: 'ET', EUR: 'AT', FKP: 'FK', FJD: 'FJ', GMD: 'GM', GEL: 'GE',
    GHS: 'GH', GIP: 'GI', GTQ: 'GT', GNF: 'GN', GYD: 'GY', HTG: 'HT', HNL: 'HN', HKD: 'HK',
    HUF: 'HU', ISK: 'IS', INR: 'IN', IDR: 'ID', ILS: 'IL', JMD: 'JM', JPY: 'JP', JOD: 'JO',
    KZT: 'KZ', KES: 'KE', KWD: 'KW', KGS: 'KG', LAK: 'LA', LBP: 'LB', LSL: 'LS', LRD: 'LR',
    LYD: 'LY', MOP: 'MO', MKD: 'MK', MGA: 'MG', MWK: 'MW', MYR: 'MY', MVR: 'MV', MRO: 'MR',
    MUR: 'MU', MXN: 'MX', MDL: 'MD', MNT: 'MN', MAD: 'MA', MZN: 'MZ', NAD: 'NA', NPR: 'NP',
    NZD: 'NZ', NIO: 'NI', NGN: 'NG', NOK: 'NO', OMR: 'OM', PKR: 'PK', PAB: 'PA', PGK: 'PG',
    PYG: 'PY', PEN: 'PE', PHP: 'PH', PLN: 'PL', QAR: 'QA', RON: 'RO', RWF: 'RW', SHP: 'SH',
    WST: 'WS', STN: 'ST', SAR: 'SA', RSD: 'RS', SCR: 'SC', SLL: 'SL', SGD: 'SG', SBD: 'SB',
    SOS: 'SO', ZAR: 'ZA', KRW: 'KR', LKR: 'LK', SRD: 'SR', SZL: 'SZ', SEK: 'SE', CHF: 'CH',
    TJS: 'TJ', TZS: 'TZ', THB: 'TH', TTD: 'TT', TND: 'TN', TRY: 'TR', TMT: 'TM', UGX: 'UG',
    UAH: 'UA', AED: 'AE', USD: 'US', UYU: 'UY', UZS: 'UZ', VUV: 'VU', VND: 'VN', XOF: 'SN',
    ZMW: 'ZM', ZWL: 'ZW', AOA: 'AO', TWD: 'TW'
  }
  return customMap[currency] || currency.substring(0, 2)
}
